import { addComponent, type EntityId, type World } from 'bitecs'
import {
  ActionComponent,
  AliveComponent,
  BlockerComponent,
  BlindComponent,
  ConsumableComponent,
  DeadComponent,
  ActorComponent,
  EquippableComponent,
  EquipmentComponent,
  CorpseComponent,
  SuitStatsComponent,
  InfoComponent,
  ItemComponent,
  LightComponent,
  OwnerComponent,
  PlayerComponent,
  PositionComponent,
  RemoveComponent,
  RenderableComponent,
  RenderLayerBlockerComponent,
  RenderLayerGroundComponent,
  RenderLayerItemComponent,
  RenderLayerAboveComponent,
  KeyComponent,
  StatsComponent,
  TargetingComponent,
  WantAttackComponent,
  WantCauseEffectComponent,
  WantUseItemComponent,
  WeaponComponent,
  type Component,
  DoorComponent,
  MeleeWeaponComponent,
  RangedWeaponComponent,
  EnragedComponent,
  AnimationComponent,
  FieldOfViewComponent,
  PathfinderComponent,
  CauseEffectComponent,
  InteractableComponent,
  WantInteractComponent,
} from '.'

export const WorldComponents: Component<any>[] = [
  ActionComponent,
  AliveComponent,
  EnragedComponent,
  AnimationComponent,
  BlockerComponent,
  CauseEffectComponent,
  BlindComponent,
  ConsumableComponent,
  DeadComponent,
  DoorComponent,
  ActorComponent,
  EquippableComponent,
  EquipmentComponent,
  FieldOfViewComponent,
  CorpseComponent,
  SuitStatsComponent,
  InfoComponent,
  InteractableComponent,
  ItemComponent,
  LightComponent,
  MeleeWeaponComponent,
  OwnerComponent,
  PathfinderComponent,
  PlayerComponent,
  PositionComponent,
  RangedWeaponComponent,
  RemoveComponent,
  RenderableComponent,
  RenderLayerGroundComponent,
  RenderLayerItemComponent,
  RenderLayerBlockerComponent,
  RenderLayerAboveComponent,
  KeyComponent,
  StatsComponent,
  TargetingComponent,
  WantAttackComponent,
  WantInteractComponent,
  WantUseItemComponent,
  WantCauseEffectComponent,
  WeaponComponent,
]

const WorldComponentNames: string[] = [
  'ActionComponent',
  'AliveComponent',
  'EnragedComponent',
  'AnimationComponent',
  'BlockerComponent',
  'CauseEffectComponent',
  'BlindComponent',
  'ConsumableComponent',
  'DeadComponent',
  'DoorComponent',
  'ActorComponent',
  'EquippableComponent',
  'EquipmentComponent',
  'FieldOfViewComponent',
  'CorpseComponent',
  'SuitStatsComponent',
  'InfoComponent',
  'InteractableComponent',
  'ItemComponent',
  'LightComponent',
  'MeleeWeaponComponent',
  'OwnerComponent',
  'PathfinderComponent',
  'PlayerComponent',
  'PositionComponent',
  'RangedWeaponComponent',
  'RemoveComponent',
  'RenderableComponent',
  'RenderLayerGroundComponent',
  'RenderLayerItemComponent',
  'RenderLayerBlockerComponent',
  'RenderLayerAboveComponent',
  'KeyComponent',
  'StatsComponent',
  'TargetingComponent',
  'WantAttackComponent',
  'WantInteractComponent',
  'WantUseItemComponent',
  'WantCauseEffectComponent',
  'WeaponComponent',
]

export const getDataFromComponent = (
  entity: EntityId,
  componentType: Component<any>,
) => {
  const index = WorldComponents.indexOf(componentType)

  const componentData = {
    componentType: WorldComponentNames[index],
    data: componentType.values[entity],
  }

  return componentData
}

export const setDataForComponent = (
  world: World,
  entity: EntityId,
  componentType: string,
  data: any,
) => {
  const componentNameIndex = WorldComponentNames.indexOf(componentType)

  if (componentNameIndex >= 0) {
    const component = WorldComponents[componentNameIndex]
    addComponent(world, entity, component)
    component.values[entity] = data
  }
}
